### ISSUE TITLE
random with length does not work

### ISSUE THREAD

**Issue by anthonyraymond** [mifmif/Generex#42]
`new Generex("[A]").random(10, 10);`
produce : "A"

`new Generex("[A]{10}").random(5, 5);`
produces : "AAAAAAAAAA"

The `random(int)` does not seams to work as weel.

Tested version `1.0.2` and `1.0.1`

**Comment by jubil** [comment]
It's normal. There is no alternative to AAAAAAAAAA.
Maybe you should try something like this: 'A{1,10}' or 'A+'

**Comment by anthonyraymond** [comment]
I don't feel like it's normal. i mean,

`new Generex("[A]").random(10, 10);`
produce : "A"
i expected it to be "AAAAAAAAAA"




`new Generex("[A]{10}").random(5, 5);`
produces : "AAAAAAAAAA"
i expected it to be "AAAAA"

**Comment by jubil** [comment]
`new Generex("[A]{10}").random(5, 5);`
can't produce "AAAAA" because "AAAAA" dont match the regular expression _(regex)_ "[A]{10}"

In order for the function to work as you wish, you must use regex "A +". For example :
`new Generex("A+").random(10, 10)` => AAAAAAAAAA
`new Generex("A+").random(5, 5)` => AAAAA
`new Generex("A+").random(1, 1)` => A
`new Generex("A+").random(1, 3)` => A or AA or AAA

I advise you to use the site https://regex101.com/ to train you to use regular expressions

**Comment by anthonyraymond** [comment]
Ok, i understand :)
Thanks for your explanation
